export default [{
  username: 'Karan',
  location: 'Durham, US',
  headline: 'Great Product',
  review: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  rating: 4,
  gist: 'Runs Large',
}, {
  username: 'Alanah',
  location: 'Denver, Colorado',
  headline: 'Great Product',
  review: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  rating: 5,
  gist: 'Runs Large',
}, {
  username: 'Gayatri',
  location: 'Bolts, US',
  headline: 'Great',
  review: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  rating: 4,
  gist: 'Runs Small',
}, {
  username: 'Gautam',
  location: 'Durham, US',
  headline: 'Product',
  review: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  rating: 3,
  gist: 'Easy to use',
}, {
  username: 'Ashok',
  location: 'Durham, US',
  headline: 'Great Product',
  review: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  rating: 5,
  gist: 'Comfortable',
}];
